name: inspector

services:
  fastapi:
    build:
      context: .
      dockerfile: Dockerfile.fastapi
    image: inspector/fastapi:latest
    container_name: inspector-fastapi
    env_file:
      - .env
    ports:
      - "8997:8000"
    volumes:
      - ./pyproject.toml:/app/pyproject.toml
      - ./poetry.lock:/app/poetry.lock
      - ./.env:/app/.env
      - ./model:/app/model
      - ./controller:/app/controller
      - ./modules:/app/modules
      - ./view/api:/app/view/api
    healthcheck:
      test: ["CMD-SHELL", "curl --fail http://localhost:8000/health || exit 1"]
    depends_on:
      - redis

  streamlit:
    build:
      context: .
      dockerfile: Dockerfile.streamlit
    image: inspector/streamlit:latest
    container_name: inspector-streamlit
    env_file:
      - .env
    ports:
      - "8998:8501"
    volumes:
      - ./pyproject.toml:/app/pyproject.toml
      - ./poetry.lock:/app/poetry.lock
      - ./.env:/app/.env
      - ./view/streamlit_app:/app/view/streamlit_app
    healthcheck:
      test: ["CMD-SHELL", "curl --fail http://localhost:8501/_stcore/health || exit 1"]
    depends_on:
      - redis

  redis:
    image: redis/redis-stack-server:latest
    container_name: inspector-redis
    ports:
      - "8999:6379"
    volumes:
      - redis-data-inspector:/data

  mkdocs:
    build:
      context: .
      dockerfile: Dockerfile.mkdocs
    image: inspector/mkdocs:latest
    container_name: inspector-mkdocs
    ports:
      - "8996:80"
    volumes:
      - ./site:/usr/share/nginx/html

  tika:
    image: apache/tika:latest
    container_name: inspector-tika
    ports:
      - "8995:9998"
    environment:
      - TIKA_SERVER_ENDPOINT=http://localhost:9998/
    healthcheck:
      test: ["CMD-SHELL", "curl --fail http://localhost:9998/ || exit 1"]

  nginx:
    image: nginx:latest
    container_name: inspector-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - streamlit
    restart: always
  
volumes:
  redis-data-inspector:
