FROM python:3.13.0-slim

WORKDIR /app

COPY . .

RUN pip install --trusted-host pypi.org --trusted-host pypi.python.org --trusted-host files.pythonhosted.org --no-cache-dir mkdocs mkdocs-material mkdocstrings-python mkdocs-include-markdown-plugin

EXPOSE 8996

CMD ["mkdocs", "serve", "--dirtyreload", "-a", "0.0.0.0:8996"]